spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://192.168.174.131:3306/canal?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200

  rabbitmq:
    host: 192.168.174.131
    port: 5672
    username: admin
    password: admin
